Alan Hurtarte 19000590

Hilda Eunice G. Rodas Rivas  19000626

---

In [1]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

In [4]:
X = np.random.rand(5, 1)
X

array([[0.74167358],
       [0.5280029 ],
       [0.26455482],
       [0.51822618],
       [0.40508215]])

In [5]:
Y = np.random.rand(5, 2)
Y

array([[0.35378297, 0.41034087],
       [0.09607225, 0.24018357],
       [0.61233917, 0.6058722 ],
       [0.22028312, 0.1393434 ],
       [0.23995117, 0.74401442]])

In [7]:
Z = np.random.rand(5, 3)
Z

array([[0.84832086, 0.0893905 , 0.39873166],
       [0.57311376, 0.75581678, 0.44385608],
       [0.11081784, 0.79178405, 0.48780049],
       [0.55729029, 0.06648682, 0.13964227],
       [0.96082586, 0.9616631 , 0.27334521]])

In [14]:
poly = PolynomialFeatures(3)
x_pol = poly.fit_transform(X)
x_pol.shape

(5, 4)

In [17]:
x_pol

array([[1.        , 0.74167358, 0.55007969, 0.40797957],
       [1.        , 0.5280029 , 0.27878706, 0.14720037],
       [1.        , 0.26455482, 0.06998925, 0.01851599],
       [1.        , 0.51822618, 0.26855838, 0.13917398],
       [1.        , 0.40508215, 0.16409155, 0.06647056]])

In [15]:
poly = PolynomialFeatures(3)
y_pol = poly.fit_transform(Y)
y_pol.shape

(5, 10)

In [18]:
y_pol

array([[1.00000000e+00, 3.53782972e-01, 4.10340871e-01, 1.25162392e-01,
        1.45171613e-01, 1.68379630e-01, 4.42803229e-02, 5.13592448e-02,
        5.95698462e-02, 6.90930442e-02],
       [1.00000000e+00, 9.60722512e-02, 2.40183567e-01, 9.22987744e-03,
        2.30749760e-02, 5.76881460e-02, 8.86735104e-04, 2.21686489e-03,
        5.54223005e-03, 1.38557447e-02],
       [1.00000000e+00, 6.12339172e-01, 6.05872196e-01, 3.74959262e-01,
        3.70999279e-01, 3.67081118e-01, 2.29602244e-01, 2.27177391e-01,
        2.24778148e-01, 2.22404243e-01],
       [1.00000000e+00, 2.20283117e-01, 1.39343403e-01, 4.85246515e-02,
        3.06949991e-02, 1.94165839e-02, 1.06891615e-02, 6.76159006e-03,
        4.27714563e-03, 2.70557288e-03],
       [1.00000000e+00, 2.39951174e-01, 7.44014421e-01, 5.75765657e-02,
        1.78527134e-01, 5.53557459e-01, 1.38155645e-02, 4.28377952e-02,
        1.32826762e-01, 4.11854732e-01]])

In [16]:
poly = PolynomialFeatures(3)
z_pol = poly.fit_transform(Z)
z_pol.shape

(5, 20)

In [19]:
z_pol

array([[1.00000000e+00, 8.48320864e-01, 8.93904967e-02, 3.98731663e-01,
        7.19648289e-01, 7.58318234e-02, 3.38252389e-01, 7.99066089e-03,
        3.56428214e-02, 1.58986939e-01, 6.10492658e-01, 6.43297179e-02,
        2.86946559e-01, 6.77864435e-03, 3.02365490e-02, 1.34871938e-01,
        7.14289146e-04, 3.18612951e-03, 1.42119214e-02, 6.33931266e-02],
       [1.00000000e+00, 5.73113760e-01, 7.55816782e-01, 4.43856076e-01,
        3.28459381e-01, 4.33168998e-01, 2.54380025e-01, 5.71259008e-01,
        3.35473871e-01, 1.97008217e-01, 1.88244591e-01, 2.48255113e-01,
        1.45788692e-01, 3.27396398e-01, 1.92264692e-01, 1.12908120e-01,
        4.31767145e-01, 2.53556782e-01, 1.48902116e-01, 8.74432940e-02],
       [1.00000000e+00, 1.10817838e-01, 7.91784050e-01, 4.87800489e-01,
        1.22805932e-02, 8.77437966e-02, 5.40569956e-02, 6.26921983e-01,
        3.86232647e-01, 2.37949317e-01, 1.36090879e-03, 9.72357784e-03,
        5.99047938e-03, 6.94741387e-02, 4.28014669e-02, 2.6369

| Variables | Grado | Polinomios (shape) |
|---|---|---|
| X | 1 | (5,4) |
| Y | 2 | (5, 10) |
| Z | 3 | (5, 20) |